### ISSUE TITLE
Map legend

### ISSUE THREAD

**Issue by heboet** [israelpohl/vizlaw_frontend#12]
Eine Art Legende, in der die Bedeutung von Knotengröße, -farbe, Kantenlänge etc. erklärt sind, wäre noch gut. Ließe sich das einbauen?

**Comment by jaksz** [comment]
Ja. Kannst Du sie zusammenschreiben dann paste ichs rein?

**Comment by heboet** [comment]
- Node Size =  degree of incoming citations (i.e. number of other cases referring to the specific case)
- Node Color = the court's level in the court hierarchy (from light red for district courts to dark red for federal courts)
- Edge Length = time distance of the cases connected by the edge

**Comment by jaksz** [comment]
fixed in #35
