### ISSUE TITLE
Range Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by heboet** [israelpohl/vizlaw_frontend#17]
Wenn man eine zweite Entscheidung aus den Suchergebnissen auf den Arbeitsbereich bringen möchte, tut sich nichts mehr ...

![image](https://user-images.githubusercontent.com/38218641/54472437-c70c1580-47c8-11e9-8002-099fcf8ccf1c.png)

**Comment by jaksz** [comment]
ok also das problem erscheint wohl dann, wenn zu viele nodes eingeblendet werden sollen. @heboet ist das ein safari screenshot? bei safari funktionieren manche suchergebnisse, wohl immer dann, wenn die anzahl der nodes gering ist. wenn zu viele nodes eingeblendet werden müssen, gibts bei safari diese fehlermeldung. bei chrome scheint es immer zu funktionieren. safari wird wohl einen niedrigeren maximum call stack wert haben.

**Comment by jaksz** [comment]
ich hab den fehler jetzt weiter isoliert, er passiert dann, wenn der node eingeblendet werden soll, der "das safari-fass zum überlaufen bringt".

der fehler passiert in der netzwerk-visualisierung-library, die wir verwenden, und nicht in unserem code. daher wäre ein fix voraussichtlich sehr aufwendig. google führt hier auch zu nichts.

daher sollten wir für new york das produkt zunächst nur als chrome-kompatibel vermarkten:

![屏幕快照 2019-04-23 01 17 32](https://user-images.githubusercontent.com/13822469/56513629-a4a6ae00-6565-11e9-98d3-935d8b0f95d9.png)

**Comment by jaksz** [comment]
fixed in #32
