### ISSUE TITLE
Page Layout

### ISSUE THREAD

**Issue by iskaleade** [israelpohl/vizlaw_frontend#19]
ich fände es gut, wenn schon beim Öffnen der App die spätere Arbeitsplatzstruktur erkennbar wäre - bisher finde ich die Seite noch sehr "roh" beim ersten Besuch. Also zB. schon die Bereiche andeuten, evtl. mit Titel o.ä. versehen und da etwas Struktur reinbringen, dann kann auch das Impressum einen Platz bekommen. Oder ist das schon geplant?

**Comment by iskaleade** [comment]
und für die mobile Ansicht: Spalten untereinander anordnen

**Comment by heboet** [comment]
Und das Logo mit Schriftzug verkleinern? Oder Logo und Schriftzug horizontal anordnen?

**Comment by jaksz** [comment]
wird mit #40 gefixt werden
