### ISSUE TITLE
Improvement: "Please Wait"-Notice, Hourglass Symbol etc. when adding new nodes

### ISSUE THREAD

**Issue by heboet** [israelpohl/vizlaw_frontend#21]
"Wenn ein Urteil aus der Suche angeklickt wurde, muss der Nutzer über das Warten informiert werden (Ladekringel, PopUp: „Übersicht wird aktualisiert“, o.Ä.)"

**Comment by jaksz** [comment]
gibt jetzt einen globalen ladekringel für alle ladevorgänge:

![屏幕快照 2019-04-23 01 39 02](https://user-images.githubusercontent.com/13822469/56514718-a2921e80-6568-11e9-9020-9331b156e636.png)

**Comment by jaksz** [comment]
fixed in #33
